# Generated by Django 3.2.7 on 2022-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='bugungi_foyda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistika',
            name='bugungi_savdo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistika',
            name='bugungi_zarar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistika',
            name='umumiy_foyda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
