# Generated by Django 4.0.5 on 2022-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=69)),
                ('firma_nomi', models.CharField(blank=True, max_length=69, null=True)),
                ('kel_narxi', models.IntegerField(blank=True, null=True)),
                ('sot_narxi', models.IntegerField(blank=True, null=True)),
                ('kel_soni', models.SmallIntegerField(blank=True, null=True)),
                ('foyda', models.IntegerField(blank=True, null=True)),
                ('zarar', models.IntegerField(blank=True, null=True)),
                ('qoldiq', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nasiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_nomi', models.CharField(max_length=69)),
                ('summasi', models.IntegerField(blank=True, null=True)),
                ('dokon_nomi', models.CharField(blank=True, max_length=69, null=True)),
                ('xodim_ismi', models.CharField(max_length=25)),
            ],
        ),
    ]
