# Generated by Django 4.0.5 on 2022-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='blog_narxi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='optm_narxi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
