# Generated by Django 4.0.5 on 2022-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsulotlar', '0002_mahsulot_blog_narxi_mahsulot_optm_narxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='blog_narxi',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='blogi',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='kilosi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
